import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from './Components/Navbar'
import Main from './Components/Main'
import Title from './Components/Title'
import Action from './Components/Action'
import Splide from './Components/Splide'
import Layout from './Components/Layout'
import  {useState} from 'react'

export default function Home() {
    const [mutedVideo, setMutedVideo] = useState(false);
  return (
    <div className='container'>
      <Head>
        <title>- Tamgagvi Tur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar setMutedVideo={setMutedVideo} mutedVideo={mutedVideo}/> 
      <Main mutedVideo={mutedVideo} />
      <Title />
      <Action />
      <Splide />
    </div>
  )
}
