import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from './Components/Navbar'
import Main from './Components/Main'
import Title from './Components/Title'
import Action from './Components/Action'
import Splide from './Components/Splide'
import Layout from './Components/Layout'

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>- HOME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <Title />
      <Action />
      <Splide />
    </div>
  )
}
